name: maya_maya_architecture
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  change_app_package_name: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  dio: ^5.4.3+1
  either_dart: ^1.0.0

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

